### ISSUE TITLE
`MathFluxExtensions#sumAsDouble` returns a `Mono<Float>`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-kotlin#32]
Since the introduction of the method in 1.1.5, it returns a `Mono<Float>` and uses `sumFloat` under the cover, basically making it an alias of `sumAsFloat`.

I would consider this as a bug and not a breaking change, it should be fixed asap to return a `Mono<Double>` as stated in the documentation, and call `sumDouble`.

**Comment by kiwisincebirth** [comment]
Happy to fix this issue, if you like.

**Comment by kiwisincebirth** [comment]
Please see PR. Think the bug in code was an oversight.
